### 학생 가입
POST http://localhost:8080/student/save
Content-Type: application/json

{
  "studentName": "dsad",
  "studentNumber": "Asdsad"
}

### 과목 신청
POST http://localhost:8080/course
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 1,
  "semester": "2023학년 1학기"
}

### 과목 취소
DELETE http://localhost:8080/course
Content-Type: application/json

{
  "enrollmentId": 18
}